-- Generic Community Agent catalog seed. Contains no user data.
-- Safe to run repeatedly.

INSERT INTO public."cloud_agent_versions_v3"("id","agent_family_id","content_hash","payload_json") VALUES('general_agent_1_v1','general_agent_1','','{}') ON CONFLICT(id) DO UPDATE SET "agent_family_id"=excluded."agent_family_id","content_hash"=excluded."content_hash","payload_json"=excluded."payload_json";
INSERT INTO public."cloud_agent_versions_v3"("id","agent_family_id","content_hash","payload_json") VALUES('general_agent_2_v1','general_agent_2','','{}') ON CONFLICT(id) DO UPDATE SET "agent_family_id"=excluded."agent_family_id","content_hash"=excluded."content_hash","payload_json"=excluded."payload_json";
INSERT INTO public."cloud_agent_versions_v3"("id","agent_family_id","content_hash","payload_json") VALUES('general_agent_3_v1','general_agent_3','','{}') ON CONFLICT(id) DO UPDATE SET "agent_family_id"=excluded."agent_family_id","content_hash"=excluded."content_hash","payload_json"=excluded."payload_json";
INSERT INTO public."cloud_agent_versions_v3"("id","agent_family_id","content_hash","payload_json") VALUES('general_agent_v1','general_agent','','{}') ON CONFLICT(id) DO UPDATE SET "agent_family_id"=excluded."agent_family_id","content_hash"=excluded."content_hash","payload_json"=excluded."payload_json";
INSERT INTO public."cloud_agent_versions_v3"("id","agent_family_id","content_hash","payload_json") VALUES('ppt_v1','ppt','','{}') ON CONFLICT(id) DO UPDATE SET "agent_family_id"=excluded."agent_family_id","content_hash"=excluded."content_hash","payload_json"=excluded."payload_json";
INSERT INTO public."cloud_agent_versions_v3"("id","agent_family_id","content_hash","payload_json") VALUES('secretary_agent_v1','secretary_agent','','{}') ON CONFLICT(id) DO UPDATE SET "agent_family_id"=excluded."agent_family_id","content_hash"=excluded."content_hash","payload_json"=excluded."payload_json";
INSERT INTO public."cloud_agent_families_v3"("id","department_id","name","role","payload_json","status","routable","current_version_id","instance_kind","recruitable","default_for_new_user","quota_cost","classification_version") VALUES('general_agent','general','Generalist','agent','{"name":"Generalist"}','active',TRUE,'general_agent_v1','employee',TRUE,TRUE,1,'employee_recruitment_phase_a_v1') ON CONFLICT(id) DO UPDATE SET "department_id"=excluded."department_id","name"=excluded."name","role"=excluded."role","payload_json"=excluded."payload_json","status"=excluded."status","routable"=excluded."routable","current_version_id"=excluded."current_version_id","instance_kind"=excluded."instance_kind","recruitable"=excluded."recruitable","default_for_new_user"=excluded."default_for_new_user","quota_cost"=excluded."quota_cost","classification_version"=excluded."classification_version";
INSERT INTO public."cloud_agent_families_v3"("id","department_id","name","role","payload_json","status","routable","current_version_id","instance_kind","recruitable","default_for_new_user","quota_cost","classification_version") VALUES('general_agent_1','general','Generalist','agent','{"name":"Generalist","metadata":{"summary":"可从人才市场招募的通用执行 Agent，独立处理问答、分析、写作、代码和文件任务。","description":"可从人才市场招募的通用执行 Agent，独立处理问答、分析、写作、代码和文件任务。","capabilityTags":["通用问答与分析","文件和代码任务处理","跨领域问题求解"]}}','retired',FALSE,'general_agent_1_v1','unavailable',FALSE,FALSE,0,'employee_recruitment_phase_a_v1') ON CONFLICT(id) DO UPDATE SET "department_id"=excluded."department_id","name"=excluded."name","role"=excluded."role","payload_json"=excluded."payload_json","status"=excluded."status","routable"=excluded."routable","current_version_id"=excluded."current_version_id","instance_kind"=excluded."instance_kind","recruitable"=excluded."recruitable","default_for_new_user"=excluded."default_for_new_user","quota_cost"=excluded."quota_cost","classification_version"=excluded."classification_version";
INSERT INTO public."cloud_agent_families_v3"("id","department_id","name","role","payload_json","status","routable","current_version_id","instance_kind","recruitable","default_for_new_user","quota_cost","classification_version") VALUES('general_agent_2','general','Generalist','agent','{"name":"Generalist","metadata":{"summary":"可从人才市场招募的通用执行 Agent，独立处理问答、分析、写作、代码和文件任务。","description":"可从人才市场招募的通用执行 Agent，独立处理问答、分析、写作、代码和文件任务。","capabilityTags":["通用问答与分析","文件和代码任务处理","跨领域问题求解"]}}','retired',FALSE,'general_agent_2_v1','unavailable',FALSE,FALSE,0,'employee_recruitment_phase_a_v1') ON CONFLICT(id) DO UPDATE SET "department_id"=excluded."department_id","name"=excluded."name","role"=excluded."role","payload_json"=excluded."payload_json","status"=excluded."status","routable"=excluded."routable","current_version_id"=excluded."current_version_id","instance_kind"=excluded."instance_kind","recruitable"=excluded."recruitable","default_for_new_user"=excluded."default_for_new_user","quota_cost"=excluded."quota_cost","classification_version"=excluded."classification_version";
INSERT INTO public."cloud_agent_families_v3"("id","department_id","name","role","payload_json","status","routable","current_version_id","instance_kind","recruitable","default_for_new_user","quota_cost","classification_version") VALUES('general_agent_3','general','Generalist','agent','{"name":"Generalist","metadata":{"summary":"可从人才市场招募的通用执行 Agent，独立处理问答、分析、写作、代码和文件任务。","description":"可从人才市场招募的通用执行 Agent，独立处理问答、分析、写作、代码和文件任务。","capabilityTags":["通用问答与分析","文件和代码任务处理","跨领域问题求解"]}}','retired',FALSE,'general_agent_3_v1','unavailable',FALSE,FALSE,0,'employee_recruitment_phase_a_v1') ON CONFLICT(id) DO UPDATE SET "department_id"=excluded."department_id","name"=excluded."name","role"=excluded."role","payload_json"=excluded."payload_json","status"=excluded."status","routable"=excluded."routable","current_version_id"=excluded."current_version_id","instance_kind"=excluded."instance_kind","recruitable"=excluded."recruitable","default_for_new_user"=excluded."default_for_new_user","quota_cost"=excluded."quota_cost","classification_version"=excluded."classification_version";
INSERT INTO public."cloud_agent_families_v3"("id","department_id","name","role","payload_json","status","routable","current_version_id","instance_kind","recruitable","default_for_new_user","quota_cost","classification_version") VALUES('ppt','ppt_department','PPT Designer','agent','{"name":"PPT Designer"}','active',TRUE,'ppt_v1','employee',TRUE,FALSE,1,'employee_recruitment_phase_a_v1') ON CONFLICT(id) DO UPDATE SET "department_id"=excluded."department_id","name"=excluded."name","role"=excluded."role","payload_json"=excluded."payload_json","status"=excluded."status","routable"=excluded."routable","current_version_id"=excluded."current_version_id","instance_kind"=excluded."instance_kind","recruitable"=excluded."recruitable","default_for_new_user"=excluded."default_for_new_user","quota_cost"=excluded."quota_cost","classification_version"=excluded."classification_version";
INSERT INTO public."cloud_agent_families_v3"("id","department_id","name","role","payload_json","status","routable","current_version_id","instance_kind","recruitable","default_for_new_user","quota_cost","classification_version") VALUES('secretary_agent','secretary_department','uBuddy','agent','{}','active',TRUE,'secretary_agent_v1','system',FALSE,FALSE,0,'employee_recruitment_phase_a_v1') ON CONFLICT(id) DO UPDATE SET "department_id"=excluded."department_id","name"=excluded."name","role"=excluded."role","payload_json"=excluded."payload_json","status"=excluded."status","routable"=excluded."routable","current_version_id"=excluded."current_version_id","instance_kind"=excluded."instance_kind","recruitable"=excluded."recruitable","default_for_new_user"=excluded."default_for_new_user","quota_cost"=excluded."quota_cost","classification_version"=excluded."classification_version";
