const node = process.execPath;

function testCase(id, file, {
  group = 'core', timeoutSeconds = 180, suites = ['all'], env = {}, successArtifacts = [], primaryReport = '',
} = {}) {
  const resolvedEnv = env;
  return {
    id, title: id.replaceAll('-', ' '), group, command: node, args: [file], timeoutSeconds, suites, env: resolvedEnv,
    successArtifacts, primaryReport,
  };
}

function nodeTestCase(id, files, { group = 'cloud', timeoutSeconds = 300, suites = ['all'] } = {}) {
  return {
    id,
    title: id.replaceAll('-', ' '),
    group,
    command: node,
    args: ['--test', '--test-reporter=spec', ...files],
    timeoutSeconds,
    suites,
  };
}

export const TEST_CASES = [
  testCase('architecture', 'scripts/architecture_check.mjs', { group: 'static', timeoutSeconds: 60, suites: ['check', 'all'] }),
  testCase('test-diagnostics', 'scripts/test_diagnostics_smoke.mjs', { group: 'static', timeoutSeconds: 60, suites: ['check', 'all'] }),
  testCase('application-logging', 'scripts/application_logging_smoke.mjs', { group: 'static', timeoutSeconds: 60, suites: ['check', 'all'] }),
  testCase('contracts', 'scripts/contracts_check.mjs', { group: 'static', timeoutSeconds: 60, suites: ['check', 'all'] }),
  testCase('repository-check', 'scripts/check.mjs', { timeoutSeconds: 900, suites: ['check', 'all'] }),
  testCase('user-agent-migration', 'scripts/user_agent_migration_rehearsal.mjs'),
  testCase('employee-instance-profile-uniqueness', 'scripts/employee_instance_profile_uniqueness_smoke.mjs', { suites: ['p0', 'p1', 'check', 'all'] }),
  testCase('employee-profile-rename-renderer', 'scripts/electron_employee_profile_rename_smoke.mjs', { group: 'renderer', timeoutSeconds: 90, suites: ['p0', 'p1', 'check', 'all'] }),
  testCase('agent-family-display-names', 'scripts/agent_family_display_names_smoke.mjs', { suites: ['p0', 'p1', 'check', 'all'] }),
  testCase('update-startup', 'scripts/update_startup_check_smoke.mjs'),
  testCase('desktop-tray-lifecycle', 'scripts/desktop_tray_lifecycle_smoke.mjs', { suites: ['p0', 'p1', 'check', 'all'] }),
  testCase('agent-execution-fifo', 'scripts/agent_execution_fifo_smoke.mjs'),
  testCase('agent-execution-parallelism', 'scripts/agent_execution_parallelism_smoke.mjs', { suites: ['p0', 'check', 'all'] }),
  testCase('agent-instance-task-routing', 'scripts/agent_instance_task_routing_smoke.mjs'),
  testCase('agent-delivery-progress', 'scripts/agent_delivery_progress_smoke.mjs'),
  testCase('task-ui-update-publisher', 'scripts/task_ui_update_publisher_smoke.mjs', { suites: ['p0', 'check', 'all'] }),
  testCase('collaboration-task-ui', 'scripts/collaboration_task_ui_smoke.mjs'),
  testCase('collaboration-group-refresh', 'scripts/collaboration_group_refresh_smoke.mjs'),
  testCase('collaboration-group-immediate-projection', 'scripts/collaboration_group_immediate_projection_smoke.mjs', { suites: ['p0', 'p1', 'check', 'all'] }),
  testCase('task-group-title', 'scripts/task_group_title_smoke.mjs', { suites: ['p0', 'p1', 'check', 'all'] }),
  testCase('chat-groups-renderer', 'scripts/chat_groups_renderer_smoke.mjs', { group: 'renderer', timeoutSeconds: 60, suites: ['p0', 'p1', 'check', 'all'] }),
  testCase('message-reactions-runtime', 'scripts/message_reactions_runtime_smoke.mjs', { group: 'check', timeoutSeconds: 30, suites: ['check', 'all'] }),
  testCase('message-reactions-renderer', 'scripts/message_reactions_renderer_smoke.mjs', { group: 'renderer', timeoutSeconds: 30, suites: ['p0', 'p1', 'check', 'all'] }),
  testCase('message-receipt-layout', 'scripts/message_receipt_layout_smoke.mjs', { group: 'renderer', timeoutSeconds: 60, suites: ['p0', 'p1', 'check', 'all'] }),
  testCase('chat-group-create-offline', 'scripts/chat_group_create_offline_runtime_smoke.mjs', { timeoutSeconds: 60, suites: ['p0', 'p1', 'check', 'all'] }),
  testCase('collaboration-file-cache', 'scripts/collaboration_file_cache_smoke.mjs', { timeoutSeconds: 60, suites: ['p0', 'p1', 'check', 'all'] }),
  testCase('profile-update-outbox', 'scripts/profile_update_outbox_smoke.mjs', { timeoutSeconds: 60, suites: ['p0', 'p1', 'check', 'all'] }),
  testCase('resumable-large-file', 'scripts/resumable_large_file_smoke.mjs', { timeoutSeconds: 120, suites: ['p0', 'p1', 'check', 'all'] }),
  testCase('attachment-format-matrix', 'scripts/attachment_format_matrix_smoke.mjs', { timeoutSeconds: 300, suites: ['p0', 'p1', 'check', 'all'] }),
  testCase('image-clipboard-actions', 'scripts/image_clipboard_actions_smoke.mjs', { group: 'renderer', timeoutSeconds: 60, suites: ['p0', 'p1', 'check', 'all'] }),
  testCase('office-preview-conversion', 'scripts/office_preview_conversion_smoke.mjs', { suites: ['p0', 'p1', 'check', 'all'] }),
  testCase('file-preview-async', 'scripts/file_preview_async_smoke.mjs', { timeoutSeconds: 60, suites: ['p0', 'p1', 'check', 'all'] }),
  testCase('office-preview-layout-e2e', 'scripts/office_preview_layout_e2e.mjs', { group: 'renderer', timeoutSeconds: 180 }),
  testCase('renderer-transition-stability', 'scripts/renderer_transition_stability_check.mjs', { group: 'renderer', timeoutSeconds: 60, suites: ['p0', 'p1', 'check', 'all'] }),
  testCase('system-notification-navigation', 'scripts/system_notification_navigation_smoke.mjs', { group: 'renderer', timeoutSeconds: 60, suites: ['p0', 'p1', 'check', 'all'] }),
  testCase('network-navigation-responsiveness', 'scripts/network_navigation_responsiveness_smoke.mjs', { group: 'renderer', timeoutSeconds: 60, suites: ['p0', 'p1', 'check', 'all'] }),
  testCase('organization-owner-transfer-renderer', 'scripts/contacts_workspace_smoke.mjs', {
    group: 'renderer', timeoutSeconds: 180, suites: ['p0', 'p1', 'check', 'all'],
    env: { JANUS_CONTACTS_ORGANIZATION_TRANSFER_UI_ONLY: '1' },
  }),
  testCase('feishu-remote-channel', 'scripts/feishu_remote_channel_smoke.mjs', { suites: ['p0', 'p1', 'check', 'all'] }),
  testCase('feishu-remote-agent-runtime', 'scripts/feishu_remote_agent_runtime_smoke.mjs', { timeoutSeconds: 180, suites: ['p0', 'p1', 'check', 'all'] }),
  testCase('janus-app-navigation', 'scripts/janus_app_navigation_smoke.mjs', { group: 'renderer', suites: ['p0', 'p1', 'check', 'all'] }),
  testCase('message-pagination', 'scripts/message_pagination_smoke.mjs', { group: 'renderer', timeoutSeconds: 60, suites: ['p0', 'p1', 'check', 'all'] }),
  testCase('renderer-message-patch-set', 'scripts/renderer_message_patch_set_smoke.mjs', { group: 'renderer', timeoutSeconds: 60, suites: ['p0', 'check', 'all'] }),
  testCase('social-conversation-summary', 'scripts/social_conversation_summary_smoke.mjs', { group: 'renderer', timeoutSeconds: 60, suites: ['p0', 'p1', 'check', 'all'] }),
  testCase('renderer-action-binding-audit', 'scripts/renderer_action_binding_audit.mjs', { group: 'renderer', timeoutSeconds: 60, suites: ['p0', 'p1', 'check', 'all'] }),
  testCase('renderer-ubuddy-work-status', 'scripts/renderer_ubuddy_work_status_smoke.mjs', { group: 'renderer', timeoutSeconds: 60, suites: ['p0', 'p1', 'check', 'all'] }),
  testCase('ubuddy-agent-work-status-projection', 'scripts/ubuddy_agent_work_status_projection_smoke.mjs', { group: 'renderer', timeoutSeconds: 60, suites: ['p0', 'p1', 'check', 'all'] }),
  testCase('deliverable-contract', 'scripts/deliverable_contract_smoke.mjs', { suites: ['p0', 'p1', 'check', 'all'] }),
  testCase('chat-run-session-isolation', 'scripts/chat_run_session_isolation_smoke.mjs'),
  testCase('file-change-strict-snapshot', 'scripts/file_change_snapshot_smoke.mjs', { timeoutSeconds: 180 }),
  testCase('file-change-snapshot-worker', 'scripts/file_change_snapshot_worker_smoke.mjs', { timeoutSeconds: 60, suites: ['p0', 'check', 'all'] }),
  testCase('chat-cancel-process-tree', 'scripts/chat_cancel_process_tree_smoke.mjs', {
    timeoutSeconds: 60, env: { JANUS_UBUDDY_CODEX_PRIMARY_V1: 'off' },
  }),
  testCase('chat-approval-cancel', 'scripts/chat_approval_cancel_smoke.mjs'),
  testCase('direct-chat-transient-retry', 'scripts/direct_chat_transient_retry_smoke.mjs'),
  testCase('codex-dynamic-tools', 'scripts/codex_dynamic_tools_smoke.mjs', { suites: ['p0', 'p1', 'check', 'all'] }),
  testCase('native-codex-plugin', 'scripts/native_codex_plugin_smoke.mjs', { suites: ['p0', 'p1', 'check', 'all'] }),
  testCase('native-codex-plugin-real', 'scripts/native_codex_plugin_real_e2e.mjs', { timeoutSeconds: 180, suites: ['p0', 'p1', 'check', 'all'] }),
  testCase('native-plugin-host-routing', 'scripts/native_plugin_host_routing_smoke.mjs', { timeoutSeconds: 180, suites: ['p0', 'p1', 'check', 'all'] }),
  testCase('native-plugin-mention', 'scripts/native_plugin_mention_smoke.mjs', { suites: ['p0', 'p1', 'check', 'all'] }),
  testCase('native-plugin-renderer', 'scripts/native_plugin_renderer_smoke.mjs', { group: 'renderer', suites: ['p0', 'p1', 'check', 'all'] }),
  testCase('plugin-directory-renderer', 'scripts/plugin_directory_renderer_smoke.mjs', { group: 'renderer', suites: ['p0', 'p1', 'check', 'all'] }),
  testCase('ubuddy-codex-primary', 'scripts/ubuddy_codex_primary_smoke.mjs', {
    timeoutSeconds: 180, suites: ['p0', 'p1', 'check', 'all'], env: { JANUS_UBUDDY_CODEX_PRIMARY_V1: 'on' },
  }),
  testCase('ubuddy-execution-mode-choice', 'scripts/ubuddy_execution_mode_choice_smoke.mjs', {
    timeoutSeconds: 180, suites: ['p0', 'p1', 'check', 'all'], env: { JANUS_UBUDDY_CODEX_PRIMARY_V1: 'on' },
  }),
  testCase('private-assistant-navigation-state', 'scripts/private_assistant_navigation_state_smoke.mjs'),
  testCase('private-assistant-core', 'scripts/private_assistant_smoke.mjs'),
  testCase('private-assistant-image-entry', 'scripts/private_assistant_image_entry_smoke.mjs'),
  testCase('ubuddy-task-query', 'scripts/ubuddy_task_query_smoke.mjs'),
  testCase('ubuddy-english-localization', 'scripts/ubuddy_english_localization_smoke.mjs', { suites: ['p0', 'p1', 'check', 'all'] }),
  testCase('ubuddy-structured-task-reference', 'scripts/ubuddy_structured_task_reference_smoke.mjs', { suites: ['p0', 'check', 'all'] }),
  testCase('ubuddy-stage0-contracts', 'scripts/ubuddy_stage0_contracts_smoke.mjs', { suites: ['p0', 'check', 'all'] }),
  testCase('ubuddy-continuous-planning', 'scripts/ubuddy_continuous_planning_smoke.mjs', { suites: ['p0', 'check', 'all'] }),
  testCase('ubuddy-bounded-delivery-rework', 'scripts/ubuddy_bounded_delivery_rework_smoke.mjs', { suites: ['p0', 'p1', 'check', 'all'] }),
  testCase('ubuddy-task-delivery-center', 'scripts/ubuddy_task_delivery_center_smoke.mjs', { timeoutSeconds: 120, suites: ['p0', 'p1', 'check', 'all'] }),
  testCase('ubuddy-intake-clarification-v2', 'scripts/ubuddy_intake_clarification_v2_smoke.mjs', { suites: ['p0', 'check', 'all'] }),
  testCase('ubuddy-recent-work-reporting', 'scripts/ubuddy_recent_work_reporting_smoke.mjs', {
    timeoutSeconds: 180, suites: ['p0', 'check', 'all'], env: { JANUS_UBUDDY_RECENT_WORK_REPORTING_V1: 'on' },
  }),
  testCase('ubuddy-message-mode', 'scripts/ubuddy_message_mode_smoke.mjs', { timeoutSeconds: 180, suites: ['p0', 'check', 'all'] }),
  testCase('ubuddy-message-mode-renderer', 'scripts/ubuddy_message_mode_renderer_smoke.mjs', { group: 'renderer', timeoutSeconds: 60, suites: ['p0', 'check', 'all'] }),
  testCase('ubuddy-capability-profile-preview', 'scripts/ubuddy_capability_profile_preview_smoke.mjs', { group: 'renderer', timeoutSeconds: 60, suites: ['p0', 'check', 'all'] }),
  testCase('ubuddy-profile-history', 'scripts/ubuddy_profile_history_smoke.mjs', { group: 'renderer', timeoutSeconds: 120, suites: ['p0', 'check', 'all'] }),
  testCase('ubuddy-stage0-public-context', 'scripts/ubuddy_full_chain_e2e.mjs', {
    timeoutSeconds: 300,
    env: { JANUS_UBUDDY_STAGE0_CONTEXT_ONLY: '1' },
    suites: ['p0', 'check', 'all'],
  }),
  testCase('ubuddy-capability-profile-social', 'scripts/ubuddy_capability_profile_social_smoke.mjs', { timeoutSeconds: 180, suites: ['p0', 'check', 'all'] }),
  testCase('ubuddy-peer-routing-shadow', 'scripts/ubuddy_peer_routing_shadow_smoke.mjs', { timeoutSeconds: 60, suites: ['p0', 'check', 'all'] }),
  testCase('ubuddy-collaboration-stage7', 'scripts/ubuddy_collaboration_stage7_smoke.mjs', { timeoutSeconds: 60, suites: ['p0', 'check', 'all'] }),
  testCase('ubuddy-collaboration-stage7-runtime', 'scripts/ubuddy_collaboration_stage7_runtime_smoke.mjs', { timeoutSeconds: 180, suites: ['p0', 'check', 'all'] }),
  testCase('ubuddy-all-stages-enabled', 'scripts/ubuddy_all_stages_enabled_e2e.mjs', { timeoutSeconds: 180, suites: ['p0', 'check', 'all'] }),
  testCase('ubuddy-planner-contract', 'scripts/ubuddy_planner_contract_smoke.mjs', { suites: ['p0', 'check', 'all'] }),
  testCase('ubuddy-organization-evolution', 'scripts/ubuddy_organization_evolution_smoke.mjs', { suites: ['p0', 'check', 'all'] }),
  testCase('ubuddy-multi-mention-auto-dispatch', 'scripts/ubuddy_multi_mention_auto_dispatch_smoke.mjs', { suites: ['p0', 'check', 'all'] }),
  testCase('ubuddy-participant-selection-policy', 'scripts/ubuddy_participant_selection_policy_smoke.mjs', { suites: ['p0', 'check', 'all'] }),
  testCase('ubuddy-routing-runtime', 'scripts/ubuddy_routing_runtime_smoke.mjs', { suites: ['p0', 'check', 'all'] }),
  testCase('ubuddy-task-runtime', 'scripts/ubuddy_task_runtime_smoke.mjs', { timeoutSeconds: 300, suites: ['p0', 'check', 'all'] }),
  testCase('delegation-markdown-file-link', 'scripts/delegation_markdown_file_link_smoke.mjs', { suites: ['p0', 'check', 'all'] }),
  testCase('ubuddy-retry-reliability', 'scripts/ubuddy_retry_reliability_smoke.mjs', { timeoutSeconds: 60, suites: ['p0', 'check', 'all'] }),
  testCase('task-update-snapshot-performance', 'scripts/task_update_snapshot_performance_smoke.mjs', { timeoutSeconds: 60, suites: ['p0', 'check', 'all'] }),
  testCase('task-artifact-service', 'scripts/task_artifact_service_smoke.mjs', { timeoutSeconds: 120, suites: ['p0', 'check', 'all'] }),
  testCase('ubuddy-sleep-wake-coordination', 'scripts/ubuddy_sleep_wake_coordination_smoke.mjs', { suites: ['p0', 'check', 'all'] }),
  testCase('ubuddy-agent-allocation', 'scripts/ubuddy_agent_allocation_smoke.mjs', { suites: ['p0', 'check', 'all'] }),
  testCase('ubuddy-dispatch-cancel', 'scripts/ubuddy_dispatch_cancel_smoke.mjs', { suites: ['p0', 'check', 'all'] }),
  testCase('ubuddy-presence-gated-dispatch', 'scripts/ubuddy_presence_gated_dispatch_smoke.mjs', { suites: ['p0', 'check', 'all'] }),
  testCase('delegation-planning-recovery', 'scripts/delegation_planning_recovery_smoke.mjs', { suites: ['p0', 'check', 'all'] }),
  testCase('task-recovery', 'scripts/task_recovery_smoke.mjs', { suites: ['p0', 'check', 'all'] }),
  testCase('ubuddy-local-workspace-isolation', 'scripts/ubuddy_local_workspace_isolation_smoke.mjs', { suites: ['p0', 'check', 'all'] }),
  testCase('ubuddy-workspace-session-isolation', 'scripts/ubuddy_workspace_session_isolation_smoke.mjs', { suites: ['p0', 'check', 'all'] }),
  testCase('ubuddy-direct-dispatch', 'scripts/ubuddy_direct_dispatch_smoke.mjs', { suites: ['p0', 'check', 'all'] }),
  testCase('social-relay-mutation-policy', 'scripts/social_relay_mutation_policy_smoke.mjs', { suites: ['p0', 'check', 'all'] }),
  testCase('social-realtime-backoff', 'scripts/social_realtime_backoff_smoke.mjs', { suites: ['p0', 'check', 'all'] }),
  testCase('ubuddy-dispatch-cloud-idempotency', 'scripts/ubuddy_dispatch_idempotency_cloud_smoke.mjs', { suites: ['p0', 'check', 'all'] }),
  testCase('ubuddy-diagnostics', 'scripts/ubuddy_diagnostics_smoke.mjs', { suites: ['p1', 'all'] }),
  testCase('ubuddy-rollout-flags', 'scripts/ubuddy_rollout_flags_smoke.mjs', { suites: ['p1', 'all'] }),
  testCase('codex-memory-no-changes', 'scripts/codex_memory_no_changes_smoke.mjs'),
  testCase('trial-provider-bundle', 'scripts/trial_provider_bundle_smoke.mjs', { suites: ['p0', 'check', 'all'] }),
  testCase('dev-trial-provider', 'scripts/dev_trial_provider_smoke.mjs', { suites: ['p0', 'check', 'all'] }),
  testCase('context-usage', 'scripts/context_usage_smoke.mjs'),
  testCase('chat-context-state-collision', 'scripts/chat_context_state_collision_smoke.mjs', { suites: ['p0', 'p1', 'check', 'all'] }),
  testCase('managed-provider-usage', 'scripts/managed_provider_usage_smoke.mjs', { suites: ['p0', 'p1', 'check', 'all'] }),
  testCase('memory-switch-file-context', 'scripts/memory_switch_file_context_smoke.mjs'),
  testCase('memory-context-pointer-repair', 'scripts/memory_context_pointer_repair_smoke.mjs', { suites: ['p0', 'p1', 'check', 'all'] }),
  testCase('memory-project-reference-upgrade', 'scripts/memory_project_reference_upgrade_smoke.mjs'),
  testCase('project-composer-selection', 'scripts/project_composer_selection_smoke.mjs'),
  testCase('project-workspace-removal', 'scripts/project_workspace_removal_smoke.mjs'),
  testCase('smtp-delivery', 'scripts/smtp_delivery_smoke.mjs'),
  testCase('sqlite-social-session', 'scripts/sqlite_social_session_smoke.mjs'),
  testCase('social-automation-ledger', 'scripts/social_automation_ledger_smoke.mjs', { suites: ['p0', 'p1', 'check', 'all'] }),
  testCase('social-relay-message-pagination', 'scripts/social_relay_message_pagination_smoke.mjs', { suites: ['p0', 'p1', 'check', 'all'] }),
  testCase('fake-codex-e2e', 'scripts/fake_codex_e2e.mjs', { timeoutSeconds: 480, env: { NODE_ENV: 'test', JANUS_UBUDDY_CODEX_PRIMARY_V1: 'off' }, suites: ['p0', 'check', 'all'] }),
  testCase('secretary-relay', 'scripts/secretary_relay_smoke.mjs', {
    timeoutSeconds: 300, env: { JANUS_UBUDDY_CODEX_PRIMARY_V1: 'off' },
  }),
  testCase('ubuddy-composer-visibility', 'scripts/ubuddy_composer_visibility_check.mjs'),
  testCase('ubuddy-ppt-delegation-contract', 'scripts/ubuddy_ppt_delegation_contract_check.mjs'),
  testCase('ppt-renderer-file-protocol', 'scripts/ppt_renderer_file_protocol_smoke.mjs', { timeoutSeconds: 240, suites: ['p0', 'check', 'all'] }),
  testCase('ppt-send-chat-workspace', 'scripts/ppt_send_chat_workspace_smoke.mjs', { timeoutSeconds: 240, suites: ['p0', 'check', 'all'] }),
  testCase('ppt-employee-cloud-catalog-reconcile', 'scripts/ppt_employee_cloud_catalog_reconcile_smoke.mjs', { suites: ['p0', 'p1', 'check', 'all'] }),
  testCase('ubuddy-full-chain', 'scripts/ubuddy_full_chain_e2e.mjs', {
    timeoutSeconds: 480,
    suites: ['p0', 'p1', 'check', 'all'],
    successArtifacts: ['ubuddy-report.json', 'ubuddy-report.md', 'ubuddy-events.jsonl'],
    primaryReport: 'ubuddy-report.md',
  }),
  testCase('ubuddy-private-workspace-ui', 'scripts/ubuddy_private_workspace_ui_smoke.mjs', { group: 'renderer', timeoutSeconds: 300 }),
  testCase('agent-conversation-memory-isolation', 'scripts/agent_conversation_memory_isolation_smoke.mjs'),
  testCase('employee-conversation-history', 'scripts/employee_conversation_history_smoke.mjs', { suites: ['p0', 'check', 'all'] }),
  testCase('agent-single-window-migration', 'scripts/agent_single_window_migration_smoke.mjs', { suites: ['p0', 'p1', 'check', 'all'] }),
  testCase('message-session-agent-consistency', 'scripts/message_session_agent_consistency_repair_smoke.mjs'),
  testCase('account-workspace', 'scripts/account_workspace_smoke.mjs', { suites: ['p0', 'check', 'all'] }),
  testCase('organization-owner-transfer', 'scripts/organization_owner_transfer_smoke.mjs', { suites: ['p0', 'p1', 'check', 'all'] }),
  testCase('organization-secondary-verification', 'scripts/organization_secondary_verification_smoke.mjs', { suites: ['p0', 'p1', 'check', 'all'] }),
  testCase('account-principal-isolation', 'scripts/account_principal_isolation_smoke.mjs', { suites: ['p0', 'p1', 'check', 'all'] }),
  testCase('account-workspace-bootstrap', 'scripts/account_workspace_bootstrap_smoke.mjs', { suites: ['p0', 'check', 'all'] }),
  testCase('friend-remark-group-rename', 'scripts/friend_remark_group_rename_check.mjs'),
  testCase('ppt-identity-consolidation', 'scripts/ppt_identity_consolidation_smoke.mjs'),
  testCase('database-maintenance-framework', 'scripts/database_maintenance_framework_smoke.mjs', { suites: ['check', 'all'] }),
  testCase('janus-clean-slate', 'scripts/janus_clean_slate_smoke.mjs', { suites: ['p0', 'p1', 'check', 'all'] }),
  testCase('database-migration-guard', 'scripts/database_migration_guard.mjs', { suites: ['p0', 'p1', 'check', 'all'] }),
  testCase('attached-skill-management', 'scripts/attached_skill_management_smoke.mjs', { suites: ['p0', 'p1', 'check', 'all'] }),
  testCase('file-output-attribution', 'scripts/file_output_attribution_smoke.mjs', { suites: ['p0', 'p1', 'check', 'all'] }),
  testCase('attached-skill-renderer', 'scripts/attached_skill_renderer_smoke.mjs', { group: 'renderer', suites: ['p0', 'p1', 'check', 'all'] }),
  testCase('organization-message-research', 'scripts/organization_message_research_smoke.mjs', { suites: ['p0', 'p1', 'check', 'all'] }),
  testCase('follower-database-contract', 'scripts/follower/database_contract_smoke.mjs', { suites: ['p0', 'p1', 'check', 'all'] }),
  testCase('follower-historical-upgrade', 'scripts/follower/historical_upgrade_smoke.mjs', { suites: ['p0', 'p1', 'check', 'all'] }),
  testCase('follower-local-service', 'scripts/follower/local_service_smoke.mjs', { suites: ['p0', 'p1', 'check', 'all'] }),
  testCase('follower-i18n-contract', 'scripts/follower/i18n_contract_smoke.mjs', { group: 'static', suites: ['p0', 'p1', 'check', 'all'] }),
  testCase('follower-renderer-shortcut', 'scripts/follower/renderer_shortcut_smoke.mjs', { group: 'renderer', suites: ['p0', 'p1', 'check', 'all'] }),
  testCase('follower-renderer-workspace', 'scripts/follower/renderer_workspace_responsive_smoke.mjs', { group: 'renderer', suites: ['p0', 'p1', 'check', 'all'] }),
  testCase('follower-renderer-start-flow', 'scripts/follower/run_renderer_start_flow_smoke.mjs', { group: 'renderer', suites: ['p0', 'p1', 'check', 'all'] }),
  testCase('follower-schedule-dst', 'scripts/follower/schedule_dst_smoke.mjs', { suites: ['p0', 'p1', 'check', 'all'] }),
  testCase('follower-schedule-recovery', 'scripts/follower/schedule_recovery_smoke.mjs', { suites: ['p0', 'p1', 'check', 'all'] }),
  testCase('follower-project-context', 'scripts/follower/project_context_smoke.mjs', { suites: ['p0', 'p1', 'check', 'all'] }),
  testCase('follower-sensitive-followup', 'scripts/follower/high_sensitivity_followup_smoke.mjs', { suites: ['p0', 'p1', 'check', 'all'] }),
  testCase('follower-authorization-revocation', 'scripts/follower/authorization_revocation_smoke.mjs', { suites: ['p0', 'p1', 'check', 'all'] }),
  testCase('follower-execution-fail-closed', 'scripts/follower/execution_fail_closed_smoke.mjs', { suites: ['p0', 'p1', 'check', 'all'] }),
  testCase('follower-atomic-commit', 'scripts/follower/atomic_commit_recovery_smoke.mjs', { suites: ['p0', 'p1', 'check', 'all'] }),
  testCase('follower-prompt-budget', 'scripts/follower/prompt_injection_budget_smoke.mjs', { suites: ['p0', 'p1', 'check', 'all'] }),
  testCase('follower-notification-correlation', 'scripts/follower/notification_correlation_smoke.mjs', { suites: ['p0', 'p1', 'check', 'all'] }),
  testCase('follower-sync-evolution', 'scripts/follower/sync_projection_evolution_smoke.mjs', { suites: ['p0', 'p1', 'check', 'all'] }),
  testCase('follower-cluster-evolution', 'scripts/follower/cluster_evolution_smoke.mjs', { suites: ['p0', 'p1', 'check', 'all'] }),
  testCase('follower-system-agent-bundle', 'scripts/follower/system_agent_bundle_smoke.mjs', { suites: ['p0', 'p1', 'check', 'all'] }),
  testCase('follower-architecture-boundary', 'scripts/follower/architecture_boundary_smoke.mjs', { group: 'static', suites: ['p0', 'p1', 'check', 'all'] }),
  testCase('database-agent-delegation-inventory', 'scripts/database_agent_delegation_inventory_smoke.mjs', { suites: ['p0', 'p1', 'check', 'all'] }),
  testCase('database-alias-context-state-v4', 'scripts/database_alias_context_state_v4_smoke.mjs', { suites: ['p0', 'p1', 'check', 'all'] }),
  testCase('database-diagnostics-v2', 'scripts/database_diagnostics_v2_smoke.mjs', { suites: ['p0', 'p1', 'check', 'all'] }),
  testCase('chat-groups-migration', 'scripts/chat_groups_migration_smoke.mjs', { suites: ['p0', 'p1', 'check', 'all'] }),
  testCase('conversation-archive-runtime', 'scripts/conversation_archive_runtime_smoke.mjs', { suites: ['p0', 'check', 'all'] }),
  testCase('database-sync-contract', 'scripts/database_sync_contract_smoke.mjs', { suites: ['p0', 'p1', 'check', 'all'] }),
  testCase('database-runtime-identity-merge', 'scripts/database_runtime_identity_merge_smoke.mjs', { suites: ['p0', 'p1', 'check', 'all'] }),
  testCase('database-shadow-preflight', 'scripts/database_shadow_preflight_smoke.mjs', { suites: ['p0', 'p1', 'check', 'all'] }),
  testCase('database-historical-upgrade-matrix', 'scripts/database_historical_upgrade_matrix.mjs', { suites: ['p0', 'p1', 'check', 'all'] }),
  testCase('database-recovery-surface', 'scripts/database_recovery_surface_smoke.mjs', { suites: ['check', 'all'] }),
  testCase('database-fresh-fallback', 'scripts/database_fresh_fallback_smoke.mjs', { suites: ['check', 'all'] }),
  testCase('database-fresh-pull-only-sync', 'scripts/database_fresh_pull_only_sync_smoke.mjs', { suites: ['p0', 'p1', 'check', 'all'] }),
  testCase('database-repair-cli', 'scripts/database_repair_cli_smoke.mjs', { timeoutSeconds: 180, suites: ['check', 'all'] }),
  testCase('recovery-renderer', 'scripts/run_recovery_renderer_smoke.mjs', { group: 'renderer', timeoutSeconds: 180 }),
  testCase('electron-database-recovery-ui-e2e', 'scripts/run_electron_database_recovery_ui_e2e.mjs', { group: 'renderer', timeoutSeconds: 180 }),
  testCase('cloud-memory-incremental-sync', 'scripts/cloud_memory_incremental_sync_smoke.mjs'),
  testCase('agent-workspace-chat-continuity', 'scripts/agent_workspace_chat_continuity_smoke.mjs', { suites: ['p0', 'check', 'all'] }),
  testCase('workspace-context-refresh', 'scripts/workspace_context_refresh_smoke.mjs', { suites: ['p0', 'check', 'all'] }),
  testCase('default-agent-memory-context', 'scripts/default_agent_memory_context_smoke.mjs', { suites: ['p0', 'check', 'all'] }),
  testCase('conversation-identity-phase6', 'scripts/conversation_identity_phase6_smoke.mjs', { suites: ['p0', 'p1', 'check', 'all'] }),
  testCase('global-ui-consistency', 'scripts/run_global_ui_consistency_smoke.mjs', {
    group: 'renderer', timeoutSeconds: 300,
    env: { JANUS_GLOBAL_UI_SCREENSHOT_DIR: '{artifactDir}/artifacts/screenshots' },
  }),
  testCase('artifact-file-actions-single-click', 'scripts/artifact_file_actions_single_click_smoke.mjs', {
    group: 'renderer', timeoutSeconds: 180,
  }),
  testCase('contact-profile-rapid-switch', 'scripts/contact_profile_rapid_switch_smoke.mjs', {
    group: 'renderer', timeoutSeconds: 180,
  }),
  testCase('renderer-dark-theme-surfaces', 'scripts/run_renderer_dark_theme_surface_smoke.mjs', {
    group: 'renderer', timeoutSeconds: 60, suites: ['p0', 'check', 'all'],
  }),
  testCase('renderer-language-switch', 'scripts/run_renderer_language_switch_smoke.mjs', {
    group: 'renderer', timeoutSeconds: 120, suites: ['p0', 'check', 'all'],
  }),
  testCase('desktop-menu-contract', 'scripts/desktop_menu_contract_smoke.mjs', {
    group: 'static', timeoutSeconds: 60, suites: ['p0', 'check', 'all'],
  }),
  testCase('renderer-context-usage', 'scripts/run_renderer_context_usage_smoke.mjs', { group: 'renderer', timeoutSeconds: 300 }),
  testCase('renderer-ubuddy-message-mode', 'scripts/run_renderer_ubuddy_message_mode_smoke.mjs', { group: 'renderer', timeoutSeconds: 180, suites: ['p0', 'check', 'all'] }),
  testCase('renderer-goal-plan-ui', 'scripts/run_renderer_goal_plan_ui_smoke.mjs', { group: 'renderer', timeoutSeconds: 180 }),
  testCase('plan-auxiliary-windows', 'scripts/run_plan_auxiliary_windows_smoke.mjs', { group: 'renderer', timeoutSeconds: 180 }),
  testCase('renderer-codex-diff', 'scripts/run_renderer_codex_diff_smoke.mjs', { group: 'renderer', timeoutSeconds: 180 }),
  testCase('renderer-ime-composition', 'scripts/run_renderer_ime_composition_smoke.mjs', { group: 'renderer', timeoutSeconds: 300 }),
  testCase('renderer-shortcut-layout', 'scripts/run_renderer_shortcut_layout_smoke.mjs', { group: 'renderer', timeoutSeconds: 300 }),
  testCase('renderer-attachment-submit', 'scripts/run_renderer_attachment_submit_smoke.mjs', { group: 'renderer', timeoutSeconds: 300 }),
  testCase('renderer-agent-conversation-isolation', 'scripts/run_renderer_agent_conversation_isolation_smoke.mjs', {
    group: 'renderer', timeoutSeconds: 300,
    env: {
      JANUS_AGENT_ISOLATION_SCREENSHOT_A: '{artifactDir}/artifacts/agent-a.png',
      JANUS_AGENT_ISOLATION_SCREENSHOT_B: '{artifactDir}/artifacts/agent-b.png',
    },
  }),
  testCase('composer-surface-draft-isolation', 'scripts/composer_surface_draft_isolation_smoke.mjs', {
    group: 'renderer', timeoutSeconds: 60, suites: ['p0', 'p1', 'check', 'all'],
  }),
  testCase('renderer-project-selection', 'scripts/run_renderer_project_selection_smoke.mjs', {
    group: 'renderer', timeoutSeconds: 300,
    env: {
      JANUS_PROJECT_SELECTION_EXISTING_SCREENSHOT: '{artifactDir}/artifacts/existing-chat.png',
      JANUS_PROJECT_SELECTION_SCREENSHOT: '{artifactDir}/artifacts/new-chat.png',
    },
  }),
  testCase('renderer-settings-update', 'scripts/run_renderer_settings_update_smoke.mjs', {
    group: 'renderer', timeoutSeconds: 480,
    env: {
      JANUS_SETTINGS_MODEL_SCREENSHOT: '{artifactDir}/artifacts/model-settings.png',
      JANUS_SETTINGS_UPDATE_SCREENSHOT: '{artifactDir}/artifacts/update-settings.png',
      JANUS_EMPLOYEE_CONTEXT_SCREENSHOT_DIR: '{artifactDir}/artifacts/employee-context',
    },
  }),
  testCase('talent-market-recruitment-ui', 'scripts/talent_market_recruitment_ui_smoke.mjs', { group: 'renderer', timeoutSeconds: 300 }),
  testCase('message-employee-home', 'scripts/run_message_employee_home_smoke.mjs', {
    group: 'renderer', timeoutSeconds: 300,
    env: { JANUS_MESSAGE_EMPLOYEE_SCREENSHOT_DIR: '{artifactDir}/artifacts/screenshots' },
  }),
  testCase('message-search-header', 'scripts/message_search_header_smoke.mjs', { suites: ['p0', 'p1', 'check', 'all'] }),
  testCase('renderer-auth', 'scripts/run_renderer_auth_smoke.mjs', {
    group: 'renderer', timeoutSeconds: 480,
    env: { JANUS_RENDERER_AUTH_SCREENSHOT: '{artifactDir}/artifacts/auth-state.png' },
  }),
  testCase('renderer-ppt-progress', 'scripts/run_renderer_ppt_progress_smoke.mjs', {
    group: 'renderer', timeoutSeconds: 480,
    env: { JANUS_PRIVATE_ASSISTANT_SCREENSHOT: '{artifactDir}/artifacts/ppt-progress.png' },
  }),
  nodeTestCase('cloud-auth-friends', ['cloud/test/auth-friends.test.mjs', 'cloud/test/database-readiness.test.mjs']),
  nodeTestCase('cloud-employees', [
    'cloud/test/cloud-contract-parity.test.mjs',
    'cloud/test/desktop-employee-immediate-sync.test.mjs',
    'cloud/test/desktop-sync-v6.test.mjs',
    'cloud/test/postgres-employee-authority.test.mjs',
    'cloud/test/postgres-sync-v6-changes.test.mjs',
    'cloud/test/postgres-sync-v6-http.test.mjs',
    'cloud/test/sqlite-employee-authority.test.mjs',
  ], { timeoutSeconds: 600 }),
  nodeTestCase('cloud-leadership', [
    'cloud/test/leadership-levels.test.mjs',
    'cloud/test/sqlite-cloud-contract.test.mjs',
    'cloud/test/sqlite-work-memory.test.mjs',
  ], { timeoutSeconds: 480 }),
  nodeTestCase('cloud-evolution', [
    'cloud/test/evolution-contracts.test.mjs',
    'cloud/test/evolution-worker-security.test.mjs',
    'cloud/test/market-support-privacy.test.mjs',
    'cloud/test/postgres-evolution-migration.test.mjs',
    'cloud/test/postgres-stage8.test.mjs',
    'cloud/test/follower-cloud-evolution.test.mjs',
    'cloud/test/sqlite-evolution-authority.test.mjs',
    'cloud/test/stage8-evolution.test.mjs',
  ], { timeoutSeconds: 600 }),
];

export function testCasesForSuite(suite = 'check') {
  return TEST_CASES.filter((item) => item.suites.includes(suite));
}
