#!/usr/bin/env node

import assert from 'node:assert/strict';
import fs from 'node:fs';
import { execFileSync } from 'node:child_process';

const read = (file) => fs.readFileSync(new URL(`../${file}`, import.meta.url), 'utf8');
const voice = read('src/renderer/voiceCallWindow.js');
const multiParty = read('src/renderer/multiPartyCallWindow.js');
const voiceCss = read('src/renderer/voiceCallWindow.css');
const chatCss = read('src/renderer/styles/chat.css');
const language = read('src/shared/uiLanguage.js');
const server = read('cloud/src/server.mjs');
const chatView = read('src/renderer/app/views/chatView.js');
const rendererApp = read('src/renderer/app/core/rendererApp.js');
const preload = read('src/preload/preload.js');
const main = read('src/main/main.js');

assert.match(voice, /getUserMedia/);
assert.match(voice, /new RTCPeerConnection/);
assert.match(voice, /serializableDescription/);
assert.match(voice, /sdp: serializableDescription\(connection\.localDescription\)/);
assert.match(voice, /onicecandidate/);
assert.match(voice, /ontrack/);
assert.match(voice, /startRingtone/);
assert.doesNotMatch(voice, /if \(!incoming \|\| ringtoneTimer\)/, 'ringtone must not be limited to incoming calls');
assert.match(voice, /callTimeout/);
assert.match(voice, /等待你接听/);
assert.match(voice, /startWaitingTimer/);
assert.match(voice, /recordVoiceCall/);
assert.match(voice, /scheduleReconnect/);
assert.match(voice, /timeoutUnansweredCall/);
assert.match(voice, /reason: 'timeout'/);
assert.match(voice, /#speaker/);
assert.match(voice, /onnegotiationneeded/);
assert.match(voice, /makingOffer/);
assert.match(voice, /setLocalDescription\(\{ type: 'rollback' \}\)/);
assert.match(voice, /restartIce/);
assert.match(voice, /flushPendingCandidates/);
assert.match(voice, /sendSignal\('mute'/);
assert.match(voice, /chooseOutputDevice/);
assert.match(voice, /createDataChannel\('voice-chat'/);
assert.match(voice, /getDisplayMedia/);
assert.match(voice, /MediaRecorder/);
assert.match(voice, /sendChatMessage/);
assert.match(voice, /log\.scrollTop = log\.scrollHeight/);
assert.match(voice, /record.*classList\.remove\('active'\)/);
assert.match(voice, /showMembers/);
assert.match(voice, /showInviteDialog/);
assert.match(voice, /data-invite-user/);
assert.match(voice, /getUserMedia\(\{ video/);
assert.match(voice, /cameraSender/);
assert.match(voice, /tile-video/);
assert.match(voice, /chooseDesktopSource/);
assert.match(voice, /listVoiceCallDesktopSources/);
assert.match(voice, /payload\.workspaceId/);
assert.match(voice, /accountWorkspaceId/);
assert.match(voice, /payload\.theme/);
assert.match(voice, /payload\.language/);
assert.match(voice, /#share-strip span.*text\('shared'\)/);
assert.match(voice, /memberTitle/);
assert.match(voice, /renameTitle/);
assert.match(voiceCss, /body\[data-theme="dark"\]/);
assert.match(voiceCss, /chat-panel #chat-log\{pointer-events:auto/);
assert.match(voiceCss, /\.tile-avatar\{display:flex;align-items:center;justify-content:center/);
assert.match(chatCss, /\.shell\.theme-dark \.voice-call-card/);
assert.match(language, /'语音通话': 'Voice Call'/);
assert.match(language, /'接听': 'Answer'/);
assert.match(chatView, /translateUiText\('发起语音通话', state\.languageMode\)/);
assert.match(chatView, /translateUiText\('语音通话', state\.languageMode\)/);
assert.match(rendererApp, /callId: signal\.callId/);
assert.match(rendererApp, /senderProfile \|\| signal\.callerProfile \|\| signal\.peer/);
assert.match(rendererApp, /signal\.senderId \|\| signal\.sender_id \|\| signal\.peerId/);
assert.match(rendererApp, /String\(signal\.type \|\| ''\) !== 'invite'/);
assert.match(rendererApp, /activeVoiceCallWorkspaceId/);
assert.match(rendererApp, /type: 'accept'/);
assert.match(rendererApp, /type: 'mute'/);
const ipc = read('src/main/ipc/registerIpcHandlers.js');
assert.match(ipc, /key: `voice-call:\$\{String\(payload\.peerId \|\| ''\)\.trim\(\)\}:\$\{String\(payload\.callId \|\| ''\)\.trim\(\)\}`/);
assert.match(server, /\/api\/social\/voice-call\/ice-servers/);
assert.match(server, /createHmac\('sha1', turnSecret\)/);
assert.match(server, /JANUS_TURN_CREDENTIAL_TTL_SECONDS/);
assert.match(server, /sharedDirectoryOrganization/);
assert.match(server, /contact_organization_members sender JOIN contact_organization_members recipient/);
assert.match(server, /const senderProfile = sender \? userPayload\(sender\)/);
assert.match(server, /callerName/);
assert.match(server, /\/api\/social\/voice-call\/record/);
assert.match(server, /persistVoiceCallSignalState/);
assert.match(server, /voice_call_sessions/);
assert.match(server, /error_code === 427/);
assert.match(server, /call_state_terminal/);
assert.match(multiParty, /startKeepalive/);
assert.match(multiParty, /janus: 'keepalive'/);
assert.match(multiParty, /request: 'leave'/);
assert.match(multiParty, /sendVoiceCallChat/);
assert.match(multiParty, /voice_call.chat/);
assert.match(server, /voice_call_record/);
assert.match(chatView, /renderVoiceCallRecordCard/);
assert.match(chatView, /call\.status === 'incoming' \? `<button type="button" class="voice-call-demo-answer"/);
assert.match(chatCss, /\.voice-call-record-card/);
assert.match(rendererApp, /signal\.callerName/);
assert.match(rendererApp, /state\.voiceCall\.status !== 'incoming'/);
assert.match(preload, /auxiliaryWindowPayload: \(value\) => ipcRenderer\.invoke\('aux-window:payload', typeof value === 'string'/);
assert.match(preload, /closeAuxiliaryWindow: \(value, submitted = false\) => ipcRenderer\.invoke\('aux-window:close', typeof value === 'string'/);
assert.equal((preload.match(/auxiliaryWindowPayload:/g) || []).length, 1, 'auxiliary payload bridge must not be shadowed');
assert.equal((preload.match(/closeAuxiliaryWindow:/g) || []).length, 1, 'auxiliary close bridge must not be shadowed');
assert.match(main, /align-items:flex-start;justify-content:flex-start/);
assert.match(main, /\.remember input\{appearance:none/);
assert.match(main, /o\.className=document\.querySelector\('\.shell\.theme-dark'\)\?'is-dark':''/);
assert.match(main, /#'\+p\.token\+'\.is-dark \.janus-close-card/);

const service = execFileSync('systemctl', ['is-active', 'coturn'], { encoding: 'utf8' }).trim();
assert.equal(service, 'active');
const turnConfig = execFileSync('sudo', ['grep', '-E', '^(use-auth-secret|cert=|pkey=)', '/etc/turnserver.conf'], { encoding: 'utf8' });
assert.match(turnConfig, /^use-auth-secret$/m);
assert.match(turnConfig, /cert=\/etc\/turnserver\/certs\/janusx\.icu\.pem/);
assert.match(turnConfig, /pkey=\/etc\/turnserver\/certs\/janusx\.icu\.key/);

console.log('voice-call contract smoke passed');
